name: Release-K8s

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "Kubernetes version"
        required: true
        default: "1.28.1"

jobs:
  publish_k8s_api_server:
    name: Build and Publish Kube-apiserver
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Checkout Kubernetes repo
        uses: actions/checkout@v3
        with:
          repository: kubernetes/kubernetes
          ref: "v${{ inputs.k8s_version }}"  
          path: "kubernetes"  
      - name: Build K8s api-server
        run: make -C kubernetes kube-apiserver KUBE_BUILD_PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64"
      - name: Prepare artifacts
        run: |
          mv ./kubernetes/_output/local/bin/linux/amd64/kube-apiserver fluvio-k8s
          TARGET=x86_64-unknown-linux-gnu
          echo $TARGET > .target
          zip fluvio-k8s-$TARGET.zip fluvio-k8s .target
          rm fluvio-k8s

          mv ./kubernetes/_output/local/bin/linux/arm64/kube-apiserver fluvio-k8s
          TARGET=aarch64-unknown-linux-gnu
          echo $TARGET > .target
          zip fluvio-k8s-$TARGET.zip fluvio-k8s .target
          rm fluvio-k8s

          mv ./kubernetes/_output/local/bin/darwin/amd64/kube-apiserver  fluvio-k8s
          TARGET=x86_64-apple-darwin
          echo $TARGET > .target
          zip fluvio-k8s-$TARGET.zip fluvio-k8s .target

          mv ./kubernetes/_output/local/bin/darwin/arm64/kube-apiserver fluvio-k8s
          TARGET=aarch64-apple-darwin
          echo $TARGET > .target
          zip fluvio-k8s-$TARGET.zip fluvio-k8s .target
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: "k8s/v${{ inputs.k8s_version }}"  
          files: |
            fluvio-k8s-x86_64-unknown-linux-gnu.zip
            fluvio-k8s-aarch64-unknown-linux-gnu.zip
            fluvio-k8s-x86_64-apple-darwin.zip
            fluvio-k8s-aarch64-apple-darwin.zip

